stages:
  - validate

commit_msg_validation:
  stage: validate
  image: alpine:latest
  script:
    - |
      commit_msg=$(git log -1 --pretty=%B)
      regex="^\[修改内容\].*\n\[关联问题\].*\n\[关联需求\].*\n\[关联车型\].*\n\[测试重点\].*$"
      if ! echo "$commit_msg" | grep -qE "$regex"; then
        echo "提交信息不符合要求，请按照以下格式填写："
        echo "[修改内容]"
        echo "[关联问题]"
        echo "[关联需求]"
        echo "[关联车型]"
        echo "[测试重点]"
        exit 1
      fi    